# Change these first
owner: cuongnd-scs # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: web1
    url: guardian-data.symcresol.com
  - name: web2
    url: www.gear71.com
  - name: web3  
    url: gear71.com
  - name: web4 
    url: captain-portal-nightly.scs71.com
  - name: web5 
    url: vqs-one-nightly.scs71.com
  - name: web6 
    url: captain-portal-staging.scs71.com
  - name: web7 
    url: dock-scheduler-staging.scs71.com
  - name: web8 
    url: vits-staging.scs71.com
  - name: web9 
    url: vqs-one-staging.scs71.com
  - name: web10  
    url: dock-scheduler-nightly.scs71.com
  - name: web11 
    url: captain-portal.scs71.com
  - name: web12  
    url: ooo.scs71.com
  - name: web13  
    url: www.scs71.com
  - name: web14  
    url: scs71.com
  - name: web15  
    url: bacs-api.scs71.com
  - name: web16  
    url: email.scs71.com
  - name: web17  
    url: dock-scheduler.scs71.com
  - name: web18  
    url: flamingo.scs71.com
  - name: web19  
    url: g.scs71.com
  - name: web20  
    url: snipe-one.scs71.com
  - name: web21  
    url: vqs-one.scs71.com
  - name: web22  
    url: cargoschedule.com
  - name: web23  
    url: demo-crawler.cargoschedule.com
  - name: web24  
    url: demo-csm.cargoschedule.com
  - name: web25  
    url: demo.cargoschedule.com
  - name: web26  
    url: nightly-com.cargoschedule.com
  - name: web27  
    url: nightly-crawler.cargoschedule.com
  - name: web28  
    url: nightly.cargoschedule.com
  - name: web29  
    url: staging-com.cargoschedule.com
  - name: web30  
    url: staging-crawler.cargoschedule.com
  - name: web31  
    url: staging.cargoschedule.com
  - name: web32  
    url: dock-scheduler.scs71.com
  - name: web33  
    url: api-flamingo-sg.symcresol.com
  - name: web34  
    url: bacs-api-nightly.symcresol.com
  - name: web35  
    url: bacs-api-sg.symcresol.com
  - name: web36
    url: error.symcresol.com
  - name: web37
    url: flamingo-nightly.symcresol.com
  - name: web38  
    url: flamingo-nyk-sg.symcresol.com
  - name: web39 
    url: flamingo-sg.symcresol.com
  - name: web40  
    url: g.symcresol.com
  - name: web41
    url: gear-staging.symcresol.com
  - name: web42  
    url: gearnightly.symcresol.com
  - name: web43  
    url: geartestingsg.symcresol.com
  - name: web44  
    url: grafana.symcresol.com
  - name: web46 
    url: homepage-nightly.symcresol.com
  - name: web47  
    url: redash.symcresol.com
  - name: web48  
    url: snipe-nightly.symcresol.com
  - name: web49  
    url: snipe-sg.symcresol.com
  - name: web50  
    url: vits-backend-staging.symcresol.com
  - name: web51  
    url: vits-nightly-be.symcresol.com
  - name: web52  
    url: vits-nightly-ecs.symcresol.com
  - name: web53  
    url: vits-nightly.symcresol.com
  - name: web54
    url: https://scs71.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/cuongnd-scs/uptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - cuongnd-scs
